name: BetterItemRestrict
main: br.com.finalcraft.betteritemrestrict.BetterItemRestrict
version: 1.0.3
author: EverNife
depend: [EverNifeCore]
api-version: 1.13

commands:
  betteritemrestrict:
    aliases: [ires, bir, bires]
  banneditems:
    description: Banned items list

permissions:
  betteritemrestrict.manage:
    default: op
  betteritemrestrict.notify:
    description: Notifications about players triggering the restriction
    default: false
  betteritemrestrict.bypass:
    description: Bypasses all protections
    default: false
  betteritemrestrict.list:
    description: Allows banneditems command use
    default: true