# Format: "MaterialName,DamageValue|ItemLabel|Reason" - Note: ",DamageValue" can be omit
# Format: "MaterialName,DamageValue|ItemLabel|Reason" - Note: ",DamageValue" can be omit
# Format: "MaterialName,DamageValue|ItemLabel|Reason" - Note: ",DamageValue" can be omit

Usage: []
Ownership: []
World: []